version: "3.8"

services:
  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/mydatabase
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - mynetwork
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mynetwork:

